version: '2'
services:
  pg84:
    image: postgres:8.4
    expose: [ 5432 ]
    ports: [ "5484:5432" ]
      
  pg90:
    image: postgres:9.0
    expose: [ 5432 ]
    ports: [ "5490:5432" ]
      
  pg91:
    image: postgres:9.1
    expose: [ 5432 ]
    ports: [ "5491:5432" ]
      
  pg92:
    image: postgres:9.2
    expose: [ 5432 ]
    ports: [ "5492:5432" ]
      
  pg93:
    image: postgres:9.3
    expose: [ 5432 ]
    ports: [ "5493:5432" ]

  pg94:
    image: postgres:9.4
    expose: [ 5432 ]
    ports: [ "5494:5432" ]

  pg95:
    image: postgres:9.5
    expose: [ 5432 ]
    ports: [ "5495:5432" ]

  pg96:
    image: postgres:9.6
    expose: [ 5432 ]
    ports: [ "5496:5432" ]
